CREATE DATABASE COLLEGE;
USE COLLEGE;

CREATE TABLE STUDENT(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR (20)
);

INSERT INTO STUDENT VALUES
(101,"ANIL",78,"C","PUNE"),
(102,"BHUMIKA",93,"A","MUMBAI"),
(103,"CHETAN",85,"B","MUMBAI"),
(104,"DHRUV",96,"A","DELHI"),
(105,"EMANUEL",12,"F","DELHI"),
(106,"FARAH",82,"B","DELHI");

SELECT *  FROM STUDENT;
SELECT CITY FROM STUDENT;

SELECT DISTINCT CITY FROM STUDENT;

SELECT *  FROM STUDENT WHERE MARKS>80;
SELECT * FROM STUDENT WHERE MARKS>80 AND CITY="MUMBAI";

SELECT *  FROM STUDENT WHERE MARKS+10>100;

SELECT * FROM STUDENT WHERE MARKS =93;

SELECT * FROM STUDENT WHERE MARKS>90 AND CITY="MUMBAI";
SELECT * FROM STUDENT WHERE MARKS>90 OR CITY="MUMBAI";

SELECT * FROM STUDENT WHERE MARKS BETWEEN 80 AND 90;

SELECT * FROM STUDENT WHERE  CITY IN ("DELHI","MUMBAI","RANCHI");

SELECT * FROM STUDENT WHERE  CITY NOT IN ("DELHI","MUMBAI");

SELECT *  FROM STUDENT LIMIT 2;

SELECT * FROM STUDENT WHERE MARKS >90 LIMIT 3;

SELECT * FROM STUDENT ORDER BY CITY ASC;

SELECT * FROM STUDENT ORDER BY CITY DESC LIMIT 2;

SELECT * FROM STUDENT ORDER BY MARKS DESC LIMIT 2;

SELECT AVG(MARKS) FROM STUDENT;

SELECT MAX(MARKS) FROM STUDENT;

SELECT COUNT(NAME) FROM STUDENT;

SELECT CITY,COUNT(NAME)
FROM STUDENT 
GROUP BY CITY;

SELECT NAME,COUNT(CITY)
FROM STUDENT
GROUP BY NAME;

SELECT CITY, AVG(MARKS)
FROM STUDENT
GROUP BY CITY
ORDER BY AVG(MARKS) DESC ;

SELECT GRADE,COUNT(ROLLNO)
FROM STUDENT
GROUP BY GRADE
ORDER BY GRADE;

SELECT CITY,COUNT(ROLLNO)
FROM STUDENT
GROUP BY CITY
HAVING MAX(MARKS) >90;

SELECT CITY
FROM STUDENT
WHERE GRADE="A"
GROUP BY CITY
HAVING MAX(MARKS)>=93
ORDER BY CITY ASC;

UPDATE STUDENT
SET GRADE="O"
WHERE GRADE="A";

SELECT*FROM STUDENT;

UPDATE STUDENT
SET MARKS =82
WHERE NAME="EMANUEL";

UPDATE STUDENT
SET GRADE="B"
WHERE MARKS BETWEEN 80 AND 90;

UPDATE STUDENT
SET MARKS = MARKS+1

UPDATE STUDENT
SET MARKS=12
WHERE ROLLNO=105;

DELETE FROM STUDENT
WHERE MARKS <33;

CREATE TABLE DEPT(
ID INT PRIMARY KEY,
NAME VARCHAR(50));

INSERT INTO DEPT VALUES
(103,"SCIENCE"),
(104,"IT"),
(105,"MATHS");


CREATE TABLE TEACHERS(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
DEPT_ID INT,
FOREIGN KEY (DEPT_ID) REFERENCES DEPT(ID)
ON UPDATE CASCADE
ON DELETE CASCADE);

INSERT INTO TEACHERS VALUES
(1,"SCIENCE",103),
(2,"IT",104),
(3,"MATHS",105);

UPDATE DEPT
SET ID =108
WHERE ID = 105;


SELECT*FROM TEACHERS;

UPDATE DEPT
SET NAME="ARTS"
WHERE NAME="SCIENCE";

SELECT*FROM DEPT;

SELECT * FROM TEACHERS;

ALTER TABLE STUDENT
ADD COLUMN AGE INT;

SELECT * FROM STUDENT;

ALTER TABLE STUDENT
DROP COLUMN AGE;

ALTER TABLE STUDENT
ADD COLUMN AGE INT NOT NULL DEFAULT 19;

ALTER TABLE STUDENT
MODIFY COLUMN AGE VARCHAR (2);

ALTER TABLE STUDENT
CHANGE COLUMN NAME FULL_NAME VARCHAR(15) NOT NULL;

SELECT * FROM STUDENT;

DELETE FROM STUDENT
WHERE MARKS<80;










